/*
 * Geolocation API
 *
 * Queries and returns location data for IP addresses
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MainHttpError struct {
	Code int32 `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
